<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kaskon.Eurocode1.Belastingen" Version="5.0.0" />
    <PackageReference Include="Kaskon.Eurocode2.BetonConstructies" Version="5.0.0" />
    <PackageReference Include="Kaskon.Profielen.Staal" Version="5.0.0" />
  </ItemGroup>

</Project>
