<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kaskon.Algemeen" Version="1.0.0" />
    <PackageReference Include="Kaskon.Toolbox.PrefabModels" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="MigraDoc.DocumentObjectModel.Core" Version="1.0.0" />
    <PackageReference Include="Plotly.Blazor" Version="6.0.2" />
	  
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Kaskon.CommonLibrary" Version="5.0.0" />
    <PackageReference Include="Kaskon.Eurocode0.Grondslagen" Version="5.0.0" />
    <PackageReference Include="Kaskon.Eurocode1.Belastingen" Version="5.0.0" />
    <PackageReference Include="Kaskon.Eurocode2.BetonConstructies" Version="5.0.0" />
    <PackageReference Include="Kaskon.Eurocode3.StaalConstructies" Version="5.0.0" />
    <PackageReference Include="Kaskon.Eurocode5.HoutConstructies" Version="5.0.0" />
    <PackageReference Include="Kaskon.ExportFactory" Version="5.0.0" />
    <PackageReference Include="Kaskon.ParametrischeProfielen" Version="5.0.0" />
    <PackageReference Include="Kaskon.Profielen.Staal" Version="5.0.0" />
    <ProjectReference Include="..\Mechanica.LiggerSB\Mechanica.LiggerSB.csproj" />
  </ItemGroup>

  <!--<ItemGroup>
    <Reference Include="CommonLibrary">
      <HintPath>..\..\Eurocode\EurocodeRazorClassLibrary\bin\Debug\net9.0\CommonLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Eurocode0.Grondslagen">
      <HintPath>..\..\Eurocode\Eurocode0.Grondslagen\bin\Debug\net9.0\Eurocode0.Grondslagen.dll</HintPath>
    </Reference>
    <Reference Include="Eurocode1.Belastingen">
      <HintPath>..\..\Eurocode\Eurocode1.Belastingen\bin\Release\net8.0\Eurocode1.Belastingen.dll</HintPath>
    </Reference>
    <Reference Include="Eurocode2.BetonConstructies">
      <HintPath>..\..\Eurocode\Eurocode2.BetonConstructies\bin\Debug\net9.0\Eurocode2.BetonConstructies.dll</HintPath>
    </Reference>
    <Reference Include="ExportFactory">
      <HintPath>..\..\Eurocode\ExportFactory\bin\Debug\net9.0\ExportFactory.dll</HintPath>
    </Reference>
    <Reference Include="Kaskon.Toolbox.PrefabModels">
      <HintPath>..\..\Kaskon.Toolbox.PrefabModels\bin\Debug\net8.0\Kaskon.Toolbox.PrefabModels.dll</HintPath>
    </Reference>
  </ItemGroup>-->

</Project>
